# Generated by Django 5.2 on 2025-11-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tiempo_preparacion', models.IntegerField(help_text='Tiempo en minutos')),
                ('instrucciones', models.TextField()),
                ('ingredientes', models.ManyToManyField(related_name='recetas', to='appRecipesStore.ingrediente')),
                ('tipo_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='appRecipesStore.tipoplato')),
            ],
        ),
    ]
