# Generated by Django 5.2.7 on 2025-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecipesStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
        migrations.AddField(
            model_name='tipoplato',
            name='descripcion',
            field=models.TextField(default='Sin descripcion'),
        ),
    ]
