# Generated by Django 5.2 on 2025-11-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecipesStore', '0002_ingrediente_descripcion_tipoplato_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen en static/appRecipesStore/img/', max_length=500, null=True),
        ),
    ]
