# Generated by Django 5.2.7 on 2025-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRecipesStore', '0003_receta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen en static/appRecipesStore/img/', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tipoplato',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta de la imagen en static/appRecipesStore/img/', max_length=500, null=True),
        ),
    ]
